"""
Utilities for converting NanoString GeoMx WTA outputs into AnnData objects.
"""

from pathlib import Path
import numpy as np
import pandas as pd
import scanpy as sc


def remove_unnamed_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Remove unnamed columns generated by CSV export."""
    return df.loc[:, ~df.columns.str.contains("^Unnamed")]


def read_geomx_wta_inputs(
    data_path,
    target_counts_file,
    probe_counts_file,
    feature_annotations_file,
    sample_annotations_file,
):
    """
    Read GeoMx WTA count matrices and annotation files.
    """
    data_path = Path(data_path)

    target_counts = pd.read_csv(data_path / target_counts_file, index_col=0)
    probe_counts = pd.read_csv(data_path / probe_counts_file, index_col=0)
    feature_annotations = pd.read_csv(data_path / feature_annotations_file)
    sample_annotations = pd.read_csv(data_path / sample_annotations_file)

    target_counts = remove_unnamed_columns(target_counts)
    probe_counts = remove_unnamed_columns(probe_counts)
    feature_annotations = remove_unnamed_columns(feature_annotations)
    sample_annotations = remove_unnamed_columns(sample_annotations)

    return target_counts, probe_counts, feature_annotations, sample_annotations


def build_geomx_wta_anndata(
    data_path,
    target_counts_file,
    probe_counts_file,
    feature_annotations_file,
    sample_annotations_file,
    roi_col="ROI",
    target_col="TargetName",
    probe_id_col="ProbeID",
    negative_col="Negative",
    neg_obsm_key="negProbes",
    counts_layer="counts",
    output_file=None,
):
    """
    Convert GeoMx WTA matrices into an AnnData object.

    Parameters
    ----------
    data_path : str or Path
        Directory containing GeoMx CSV files.
    target_counts_file : str
        Target count matrix file.
    probe_counts_file : str
        Probe count matrix file.
    feature_annotations_file : str
        Feature annotation CSV.
    sample_annotations_file : str
        Sample/ROI annotation CSV.
    roi_col : str
        Column in sample annotations containing ROI identifiers.
    target_col : str
        Column in feature annotations containing target gene names.
    probe_id_col : str
        Column in feature annotations containing probe IDs.
    negative_col : str
        Column indicating negative probes.
    neg_obsm_key : str
        AnnData obsm key for negative probe matrix.
    counts_layer : str
        AnnData layer name for raw counts.
    output_file : str, optional
        If provided, writes AnnData object to this file.

    Returns
    -------
    AnnData
    """
    data_path = Path(data_path)

    target_counts, probe_counts, feature_annotations, sample_annotations = read_geomx_wta_inputs(
        data_path=data_path,
        target_counts_file=target_counts_file,
        probe_counts_file=probe_counts_file,
        feature_annotations_file=feature_annotations_file,
        sample_annotations_file=sample_annotations_file,
    )

    required_feature_cols = {target_col, probe_id_col, negative_col}
    missing_feature_cols = required_feature_cols - set(feature_annotations.columns)

    if missing_feature_cols:
        raise ValueError(f"Missing feature annotation columns: {missing_feature_cols}")

    if roi_col not in sample_annotations.columns:
        raise ValueError(f"Missing ROI column in sample annotations: {roi_col}")

    feature_annotations[negative_col] = (
        feature_annotations[negative_col]
        .astype(str)
        .str.upper()
        .map({"TRUE": True, "FALSE": False})
    )

    sample_annotations = sample_annotations.set_index(roi_col)

    shared_rois = target_counts.columns.intersection(sample_annotations.index)

    if len(shared_rois) == 0:
        raise ValueError("No matching ROI IDs between target count matrix and sample annotations.")

    target_counts = target_counts.loc[:, shared_rois]
    sample_annotations = sample_annotations.loc[shared_rois, :]

    negative_probe_names = feature_annotations.loc[
        feature_annotations[negative_col], probe_id_col
    ].dropna()

    negative_probe_counts = probe_counts.loc[
        probe_counts.index.intersection(negative_probe_names),
        shared_rois,
    ]

    feature_annotations = feature_annotations.loc[~feature_annotations[negative_col]].copy()
    feature_annotations = feature_annotations.set_index(target_col, drop=False)

    shared_targets = target_counts.index.intersection(feature_annotations.index)

    if len(shared_targets) == 0:
        raise ValueError("No matching target genes between count matrix and feature annotations.")

    target_counts = target_counts.loc[shared_targets, :]
    feature_annotations = feature_annotations.loc[shared_targets, :]

    adata = sc.AnnData(
        X=target_counts.T.to_numpy()
    )

    adata.obs = sample_annotations.copy()
    adata.var = feature_annotations.copy()

    adata.obs_names = shared_rois.astype(str)
    adata.var_names = shared_targets.astype(str)

    adata.layers[counts_layer] = adata.X.copy()
    adata.obsm[neg_obsm_key] = negative_probe_counts.T.to_numpy()

    if output_file is not None:
        adata.write(data_path / output_file)

    return adata


def export_expression_csv(adata, output_file, counts_layer="counts"):
    """
    Export a raw counts layer to a plain ROI x gene CSV.

    Row labels are `adata.obs_names` -- the same values
    `python.abundance_extraction_utils.make_abundance_dataframe()` resets
    into the `ROI_ID` column of the cell-proportions table, so this export
    joins correctly against that table by `ROI_ID` without needing any
    GeoMx-specific ETL on the reading side (e.g. in R).

    Parameters
    ----------
    adata : AnnData
        GeoMx WTA AnnData (or a condition subset of it).
    output_file : str
        Destination CSV path.
    counts_layer : str
        Layer to export.

    Returns
    -------
    pandas.DataFrame
        The exported ROI x gene dataframe.
    """
    counts = adata.layers[counts_layer]
    if not isinstance(counts, np.ndarray):
        counts = counts.toarray()

    expression_df = pd.DataFrame(
        counts,
        index=adata.obs_names,
        columns=adata.var_names,
    )

    expression_df.to_csv(output_file)

    return expression_df


def export_negprobe_background_from_targets(
    data_path,
    target_counts_file,
    feature_annotations_file,
    output_file,
    negative_col="Negative",
    target_col="TargetName",
):
    """
    Export a per-ROI negative-probe background from the target count matrix.

    In this GeoMx WTA data the negative control targets (e.g. NegProbe-WTX)
    live as rows of the raw TargetCountMatrix, flagged by the `Negative` column
    of the feature annotations (the build in `build_geomx_wta_anndata` strips
    them out of the AnnData's expression matrix). This reads them straight from
    the raw target CSV and writes one row per ROI (index = ROI id) with a
    `background` column = the mean of that ROI's negative-target counts.

    This is the background input NanoString's SpatialDecon expects; it is
    consumed by `deconvolution_comparison/R/adapter_spatialdecon.R` via
    `load_roi_background`.

    Parameters
    ----------
    data_path : str or Path
        Directory containing the GeoMx CSV files.
    target_counts_file : str
        Target count matrix file (targets x ROI).
    feature_annotations_file : str
        Feature annotation CSV (must carry the `negative_col` flag and
        `target_col` name).
    output_file : str
        Destination CSV path.
    negative_col : str
        Column flagging negative-control features.
    target_col : str
        Column naming the target (matched against the count matrix's index).

    Returns
    -------
    pandas.DataFrame
        The exported per-ROI background dataframe.
    """
    data_path = Path(data_path)

    target_counts = pd.read_csv(data_path / target_counts_file, index_col=0)
    feature_annotations = pd.read_csv(data_path / feature_annotations_file)

    target_counts = remove_unnamed_columns(target_counts)
    feature_annotations = remove_unnamed_columns(feature_annotations)

    neg_flag = (
        feature_annotations[negative_col]
        .astype(str)
        .str.upper()
        .map({"TRUE": True, "FALSE": False})
        .fillna(False)
    )

    negative_targets = feature_annotations.loc[neg_flag, target_col].astype(str).unique()
    present_negatives = [t for t in negative_targets if t in target_counts.index]

    if len(present_negatives) == 0:
        raise ValueError(
            "export_negprobe_background_from_targets: no negative targets "
            f"(flagged by '{negative_col}') found in the target count matrix's "
            "index. Check the negative_col / target_col names."
        )

    neg_counts = target_counts.loc[present_negatives]  # negatives x ROI

    background = pd.DataFrame({"background": neg_counts.mean(axis=0)})
    background.index.name = "ROI_ID"

    background.to_csv(output_file)

    return background


def split_anndata_by_obs(adata, obs_col, values=None):
    """
    Split AnnData object by an obs column.

    Parameters
    ----------
    adata : AnnData
    obs_col : str
        Column in adata.obs.
    values : list, optional
        Values to split. If None, uses all unique values.

    Returns
    -------
    dict
        Dictionary of AnnData subsets.
    """
    if obs_col not in adata.obs.columns:
        raise ValueError(f"{obs_col} not found in adata.obs")

    if values is None:
        values = adata.obs[obs_col].dropna().unique().tolist()

    return {
        str(v): adata[adata.obs[obs_col] == v].copy()
        for v in values
    }
